Support newer Clang in CentOS 7
```
[swift/utils/build-script] ERROR: can't find clang (please install clang-3.5 or a later version)
ERROR: command terminated with a non-zero exit status 1, aborting
```

We were missing these two steps from CentOS 7 Dockerfile: 
```
RUN echo -e ". /opt/rh/sclo-git25/enable\n. /opt/rh/llvm-toolset-7/enable\n. /opt/rh/devtoolset-8/enable\n" >> /home/build-user/.bashrc
RUN sed -i -e 's/\*__block/\*__libc_block/g' /usr/include/unistd.h
```